[versions]
kotlin = "2.3.10"
agp = "9.0.1"
dokka = "2.1.0"
nexusPublish = "2.0.0"
kotest = "6.1.3"
junit = "6.0.2"
ktfmt = "0.25.0"
spotless = "8.2.1"
jacoco = "0.8.13"
googleJavaFormat = "1.22.0"
desugarJdkLibs = "2.1.5"
androidCompileSdk = "36"
androidMinSdk = "25"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
